name: ongkir_oldver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_search: 2.0.1
  dio: 4.0.6
  http: 0.13.4
  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.2.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^9.5.3+1
  firebase_core: ^1.12.0
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.0
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6
flutter: 
  uses-material-design: true
  assets:
    - assets/translates/
  fonts:
    - family: Monofett
      fonts: 
      - asset: assets/fonts/Monofett-Regular.ttf
